version: '3.9'
services:
  shell:
    build:
      context: .
      dockerfile: Dockerfile.shell
    ports:
      - '${SHELL_HOST_PORT:-4300}:4300'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CLIENT_DIST_DIR=/app/client/dist
  operations-reports:
    build:
      context: .
      dockerfile: Dockerfile.operations-reports
    ports:
      - '${OPERATIONS_HOST_PORT:-4400}:4400'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CLIENT_DIST_DIR=/app/client/dist
      - SHELL_URL=http://shell:4300
    depends_on:
      - shell
  users-and-roles:
    build:
      context: .
      dockerfile: Dockerfile.users-and-roles
    ports:
      - '${USERS_HOST_PORT:-4402}:4402'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CLIENT_DIST_DIR=/app/client/dist
      - SHELL_URL=http://shell:4300
    depends_on:
      - shell
