version: '3.9'
services:
  shell:
    build:
      context: .
      dockerfile: Dockerfile.shell
    ports:
      - '${SHELL_HOST_PORT:-4300}:4300'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CLIENT_DIST_DIR=/app/client/dist
  operations-reports:
    build:
      context: .
      dockerfile: Dockerfile.operations-reports
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CLIENT_DIST_DIR=/app/client/dist
      - SHELL_URL=http://shell:4300
      - MICROFRONT_PUBLIC_URL=http://operations-reports:4400
      - MICROFRONT_API_URL=http://operations-reports:4400
    depends_on:
      - shell
  users-and-roles:
    build:
      context: .
      dockerfile: Dockerfile.users-and-roles
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CLIENT_DIST_DIR=/app/client/dist
      - SHELL_URL=http://shell:4300
      - MICROFRONT_PUBLIC_URL=http://users-and-roles:4402
      - MICROFRONT_API_URL=http://users-and-roles:4402
    depends_on:
      - shell
