version: '3.9'
services:
  shell:
    build:
      context: .
      dockerfile: src/shell-app/Dockerfile
    ports:
      - '${SHELL_HOST_PORT:-4300}:4300'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CLIENT_DIST_DIR=/app/src/shell-app/client/dist
  operations-reports:
    build:
      context: .
      dockerfile: src/microfrontends/operations-reports/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CLIENT_DIST_DIR=/app/src/microfrontends/operations-reports/client/dist
      - SHELL_URL=http://shell:4300
      - MICROFRONT_PUBLIC_URL=http://localhost:4300/microfrontends/operations-reports
      - MICROFRONT_API_URL=http://operations-reports:4400
      - MICROFRONT_ASSET_URL=http://operations-reports:4400
    depends_on:
      - shell
  users-and-roles:
    build:
      context: .
      dockerfile: src/microfrontends/users-and-roles/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CLIENT_DIST_DIR=/app/src/microfrontends/users-and-roles/client/dist
      - SHELL_URL=http://shell:4300
      - MICROFRONT_PUBLIC_URL=http://localhost:4300/microfrontends/users-and-roles
      - MICROFRONT_API_URL=http://users-and-roles:4402
      - MICROFRONT_ASSET_URL=http://users-and-roles:4402
    depends_on:
      - shell
