# syntax=docker/dockerfile:1
FROM node:20-bullseye-slim AS runtime
ENV NODE_ENV=production
WORKDIR /app

COPY src/server ./src/server
COPY src/microfrontends/common ./src/microfrontends/common
COPY src/microfrontends/operations-reports/.env ./src/microfrontends/operations-reports/.env
COPY src/microfrontends/operations-reports/manifest.json ./src/microfrontends/operations-reports/manifest.json
COPY src/microfrontends/operations-reports/client/dist ./client/dist
COPY src/microfrontends/operations-reports/server/dist ./src/microfrontends/operations-reports/server/dist
COPY src/microfrontends/operations-reports/server/dist/data ./src/microfrontends/operations-reports/server/data
COPY src/microfrontends/operations-reports/server/dist/swagger ./src/microfrontends/operations-reports/server/swagger

EXPOSE 4400
ENV MICROFRONT_PORT=4400
CMD ["node", "src/microfrontends/operations-reports/server/dist/server.js"]
